### ISSUE TITLE
Failed to Deploy koumoul on local 

### ISSUE THREAD

**Issue by mustaphabaz** [data-fair/data-fair#141]
1) By using : [data-fair.env](https://data-fair.github.io/3/install-resources/local/data-fair.env),  [default.conf](https://data-fair.github.io/3/install-resources/full/default.conf) and [docker-compose.yaml](https://data-fair.github.io/3/install-resources/local/docker-compose.yaml)' 

![Capture du 2023-01-11 10-57-21](https://user-images.githubusercontent.com/44085902/211776021-036691b3-f350-4c2f-88f2-46416b450377.png)

2) By using 'https://github.com/data-fair/data-fair' : 

![thumbnail_image](https://user-images.githubusercontent.com/44085902/211782490-ca8357bd-588e-4b0f-9a10-bc2606a39192.png)

i think The error message is indicating that there's an issue with the router object that the code is trying to use on line 116 of the file "/Users/datategy/z-koumoul/data-fair-master/server/utils/limits.js", specifically that the object is "undefined". This could be due to a number of things, such as the import statement that brings in the router not being correct, or the module that exports the router not being set up correctly.

**Comment by albanm** [comment]
The missing file can be found here https://data-fair.github.io/3/install-resources/local/capture-seccomp.json , the link is missing from the documentation and will be added soon.

As for the nodejs error when running from source code, I don't understand it. Maybe it is due to the nodejs version v18 (I still use v16), I will check this soon and reply here with more details.

**Comment by albanm** [comment]
No, even with node v18 I don't have this error. I have no idea where it comes from.

**Comment by mustaphabaz** [comment]
> The missing file can be found here https://data-fair.github.io/3/install-resources/local/capture-seccomp.json , the link is missing from the documentation and will be added soon.sudo docker-compose build up -d
> 
> As for the nodejs error when running from source code, I don't understand it. Maybe it is due to the nodejs version v18 (I still use v16), I will check this soon and reply here with more details.

I added the file capture-seccomp.json to the folder, but I still get errors, when I try to build with `sudo docker-compose build up -d` : 
![Capture du 2023-01-11 13-25-21](https://user-images.githubusercontent.com/44085902/211808602-2363d9e8-5ee0-4ec7-a130-96cf4cd40f51.png)


and if I launch without up : 

![Capture du 2023-01-11 13-38-23](https://user-images.githubusercontent.com/44085902/211808495-e73f176b-aaa6-4708-9c63-6f426c99a78e.png)


I'm confused

**Comment by albanm** [comment]
I don't know where you got the command "docker-compose build up -d", it doesn't make sense as "up" and "build" arre 2 different docker-compose commands. The command in the documentation is "docker-compose --env-file data-fair.env up -d".

**Comment by mustaphabaz** [comment]
version 3 of the koumoul/capture service is no longer available on the hub
<img width="1091" alt="Capture d’écran 2023-01-11 à 15 43 06" src="https://user-images.githubusercontent.com/44085902/211837012-abe91804-39f2-46e3-b730-01c653cca2df.png">

**Comment by albanm** [comment]
Indeed the image was moved you can replace koumoul/capture:3 with ghcr.io/data-fair/capture:3 in the docker-compose.yml file.

Sorry about that, I will update the doc.

**Comment by mustaphabaz** [comment]
Thnx, it work.
